"""Generates src/Mdk.Formats/Scripts/ScriptOpcodes.g.cs (the script opcodes' operand layouts) from
the Godot port's tools/python/script_opcodes.json, classifying operands with its gen_script_table.

Usage: python tools/gen_opcodes.py [path to godot-mdk]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GODOT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "..", "godot-mdk")
TOOLS = os.path.join(GODOT, "tools", "python")
OUT = os.path.join(HERE, "..", "src", "Mdk.Formats", "Scripts", "ScriptOpcodes.g.cs")
END = 0xFF

sys.path.insert(0, TOOLS)
from gen_script_table import operand_code  # noqa: E402
from mdk_script_dis import NOFALL  # noqa: E402


def main():
    ops = json.load(open(os.path.join(TOOLS, "script_opcodes.json"), encoding="utf-8"))
    lines = [
        "// Generated by tools/gen_opcodes.py from godot-mdk/tools/python/script_opcodes.json. Don't edit.",
        "namespace Mdk.Formats.Scripts;",
        "",
        "/// <summary>Operand layouts of the script opcodes (see <see cref=\"ScriptDecoder\"/>).</summary>",
        "public static class ScriptOpcodes",
        "{",
        "    /// <summary>Opcode to its mnemonic.</summary>",
        "    public static readonly IReadOnlyDictionary<int, string> Mnemonics = new Dictionary<int, string>",
        "    {",
    ]
    for o in ops:
        lines.append('        [%d] = "%s",' % (o["opcode"], o["mnemonic"]))
    lines += [
        "    };",
        "",
        "    /// <summary>Opcode to its operand codes: plain types (u8, f32, pstr...), code32/data32 offsets,",
        "    /// repeat:&lt;items&gt;, action, value, cond, or opN_name for special layouts.</summary>",
        "    public static readonly IReadOnlyDictionary<int, string[]> Operands = new Dictionary<int, string[]>",
        "    {",
    ]
    for o in ops:
        if o["opcode"] == END:
            continue
        codes = ", ".join('"%s"' % operand_code(o["opcode"], a) for a in o["operands"])
        lines.append("        [%d] = [%s]," % (o["opcode"], codes))
    lines += [
        "    };",
        "",
        "    /// <summary>Opcodes that never continue with the next instruction.</summary>",
        "    public static readonly IReadOnlySet<int> NoFallthrough = new HashSet<int> { %s };" % ", ".join(str(n) for n in sorted(NOFALL)),
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
